/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FcCharVerify: typeof import('./src/components/fcCharVerify/index.vue')['default']
    FcEcharts: typeof import('./src/components/fcEcharts/index.vue')['default']
    FcFormTable: typeof import('./src/components/fcFormTable/index.vue')['default']
    FcIconSelect: typeof import('./src/components/fcIconSelect/index.vue')['default']
    FcPasswordStrength: typeof import('./src/components/fcPasswordStrength/index.vue')['default']
    FcQrCode: typeof import('./src/components/fcQrCode/index.vue')['default']
    FcQuery: typeof import('./src/components/fcQuery/index.vue')['default']
    FcSelectFilter: typeof import('./src/components/fcSelectFilter/index.vue')['default']
    FcStatistic: typeof import('./src/components/fcStatistic/index.vue')['default']
    FcTable: typeof import('./src/components/fcTable/index.vue')['default']
    FcTreeFilter: typeof import('./src/components/fcTreeFilter/index.vue')['default']
    FcTrend: typeof import('./src/components/fcTrend/index.vue')['default']
    FcUploadImg: typeof import('./src/components/fcUploadImg/index.vue')['default']
    FcUploadImgs: typeof import('./src/components/fcUploadImgs/index.vue')['default']
    FcWangEditor: typeof import('./src/components/fcWangEditor/index.vue')['default']
    FcWordVerify: typeof import('./src/components/fcWordVerify/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
